// <auto-generated />
using System;
using HotelBooking.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelBooking.DAL.Migrations
{
    [DbContext(typeof(HotelBookingDbContext))]
    partial class HotelBookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelBooking.Domain.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HotelBooking.Domain.Models.BookingExtra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("BookingExtras");
                });

            modelBuilder.Entity("HotelBooking.Domain.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HotelBooking.Domain.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Sweden",
                            CreatedAt = new DateTime(2021, 9, 26, 13, 38, 59, 992, DateTimeKind.Local).AddTicks(7723),
                            Name = "Plaza Bay Hotel",
                            ThumbnailImage = "https://picsum.photos/500"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Sweden",
                            CreatedAt = new DateTime(2021, 9, 26, 13, 38, 59, 995, DateTimeKind.Local).AddTicks(3348),
                            Name = "Stadshotellet",
                            ThumbnailImage = "https://picsum.photos/500"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Sweden",
                            CreatedAt = new DateTime(2021, 9, 26, 13, 38, 59, 995, DateTimeKind.Local).AddTicks(3498),
                            Name = "Sunkstället",
                            ThumbnailImage = "https://picsum.photos/500"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Sweden",
                            CreatedAt = new DateTime(2021, 9, 26, 13, 38, 59, 995, DateTimeKind.Local).AddTicks(3509),
                            Name = "Stugstugan",
                            ThumbnailImage = "https://picsum.photos/500"
                        });
                });

            modelBuilder.Entity("HotelBooking.Domain.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("HotelId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 9, 26, 13, 38, 59, 996, DateTimeKind.Local).AddTicks(1860),
                            HotelId = 1,
                            Score = 2.0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 9, 26, 13, 38, 59, 996, DateTimeKind.Local).AddTicks(2355),
                            HotelId = 1,
                            Score = 2.0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 9, 26, 13, 38, 59, 996, DateTimeKind.Local).AddTicks(2365),
                            HotelId = 1,
                            Score = 1.0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 9, 26, 13, 38, 59, 996, DateTimeKind.Local).AddTicks(2369),
                            HotelId = 1,
                            Score = 1.0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 9, 26, 13, 38, 59, 996, DateTimeKind.Local).AddTicks(2372),
                            HotelId = 2,
                            Score = 0.0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 9, 26, 13, 38, 59, 996, DateTimeKind.Local).AddTicks(2375),
                            HotelId = 2,
                            Score = 0.0
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 9, 26, 13, 38, 59, 996, DateTimeKind.Local).AddTicks(2379),
                            HotelId = 2,
                            Score = 2.0
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 9, 26, 13, 38, 59, 996, DateTimeKind.Local).AddTicks(2382),
                            HotelId = 2,
                            Score = 1.0
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 9, 26, 13, 38, 59, 996, DateTimeKind.Local).AddTicks(2385),
                            HotelId = 3,
                            Score = 2.0
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 9, 26, 13, 38, 59, 996, DateTimeKind.Local).AddTicks(2388),
                            HotelId = 3,
                            Score = 5.0
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 9, 26, 13, 38, 59, 996, DateTimeKind.Local).AddTicks(2392),
                            HotelId = 3,
                            Score = 2.0
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 9, 26, 13, 38, 59, 996, DateTimeKind.Local).AddTicks(2396),
                            HotelId = 3,
                            Score = 0.0
                        });
                });

            modelBuilder.Entity("HotelBooking.Domain.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HotelBooking.Domain.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<int>("PricePerNight")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 9, 26, 13, 38, 59, 996, DateTimeKind.Local).AddTicks(4515),
                            MaxCapacity = 1,
                            PricePerNight = 100,
                            Type = "Single Room"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 9, 26, 13, 38, 59, 996, DateTimeKind.Local).AddTicks(5067),
                            MaxCapacity = 2,
                            PricePerNight = 150,
                            Type = "Double Room"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 9, 26, 13, 38, 59, 996, DateTimeKind.Local).AddTicks(5077),
                            MaxCapacity = 3,
                            PricePerNight = 200,
                            Type = "Triple Room"
                        });
                });

            modelBuilder.Entity("HotelBooking.Domain.Models.Booking", b =>
                {
                    b.HasOne("HotelBooking.Domain.Models.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId");

                    b.HasOne("HotelBooking.Domain.Models.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelBooking.Domain.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId");

                    b.Navigation("Customer");

                    b.Navigation("Hotel");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelBooking.Domain.Models.BookingExtra", b =>
                {
                    b.HasOne("HotelBooking.Domain.Models.Booking", null)
                        .WithMany("BookingExtras")
                        .HasForeignKey("BookingId");
                });

            modelBuilder.Entity("HotelBooking.Domain.Models.Rating", b =>
                {
                    b.HasOne("HotelBooking.Domain.Models.Customer", "Customer")
                        .WithMany("Ratings")
                        .HasForeignKey("CustomerId");

                    b.HasOne("HotelBooking.Domain.Models.Hotel", "Hotel")
                        .WithMany("Ratings")
                        .HasForeignKey("HotelId");

                    b.Navigation("Customer");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelBooking.Domain.Models.Room", b =>
                {
                    b.HasOne("HotelBooking.Domain.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId");

                    b.HasOne("HotelBooking.Domain.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelBooking.Domain.Models.Booking", b =>
                {
                    b.Navigation("BookingExtras");
                });

            modelBuilder.Entity("HotelBooking.Domain.Models.Customer", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("HotelBooking.Domain.Models.Hotel", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelBooking.Domain.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("HotelBooking.Domain.Models.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
